---
- name: Delete Extra MikroTik Static DNS Entries
  hosts: mikrotik_router
  gather_facts: no
  roles:
    - role: mikrotik_dns
      delete_dns: true
      static_records_file: "vars/static_records.yml"