---
- name: Retrieve Static DNS Records from MikroTik Router
  community.routeros.command:
    commands:
      - /ip dns static print
  register: dns_records_raw

- name: Debug raw DNS records output
  debug:
    var: dns_records_raw.stdout_lines

- name: Initialize static_dns_parsed
  set_fact:
    static_dns_parsed: []

- name: Parse DNS record lines
  set_fact:
    static_dns_parsed: "{{ static_dns_parsed + [ dns_record ] }}"
  vars:
    parts: "{{ item.split() }}"
    dns_record: >-
      {{
        {
          'name': parts[1],
          'address': ('' if parts[2] == 'CNAME' else parts[3]),
          'ttl': (parts[3] if parts[2] == 'CNAME' else parts[4]),
          'type': parts[2]
        }
      }}
  loop: "{{ dns_records_raw.stdout_lines[0] }}"
  when:
    - not (item.startswith('Columns:') or item.startswith('#') or item.startswith(';;;'))
    - item.strip() != ''

- name: Display parsed static DNS records
  debug:
    var: static_dns_parsed

- name: Render DNS records to YAML file using template
  template:
    src: ../templates/static_dns_inventory.yml.j2
    dest: "{{template_dest}}"